import { Application } from 'express';
import usersRouter from './api/controllers/users/router';
import tenantsRouter from './api/controllers/tenants/router';
import authRouter from './api/controllers/auth/router';

import profiletypeRouter from './api/controllers/profiletype/router';
import addresstypeRouter from './api/controllers/addresstype/router';
import countryRouter from './api/controllers/country/router';
import profileRouter from './api/controllers/profile/router';
import nextofkinRouter from './api/controllers/nextofkin/router';
import addressRouter from './api/controllers/address/router';
import branchRouter from './api/controllers/branch/router';
import residentbranchRouter from './api/controllers/residentbranch/router';
import additionalnotesRouter from './api/controllers/additionalnotes/router';
import generalinfoRouter from './api/controllers/generalinfo/router';
import accommodationdetailsRouter from './api/controllers/accommodationdetails/router';
import carerskillRouter from './api/controllers/carerskill/router';
import carerspacialitiesRouter from './api/controllers/carerspacialities/router';
import roleRouter from './api/controllers/role/router';
import profileroleRouter from './api/controllers/profilerole/router';
import ratingRouter from './api/controllers/rating/router';
import availabilityRouter from './api/controllers/availability/router';
import employmentdetailsRouter from './api/controllers/employmentdetails/router';
import appointmentRouter from './api/controllers/appointment/router';
import appointedcarerRouter from './api/controllers/appointedcarer/router';
import plantypesRouter from './api/controllers/plantypes/router';
import serviceRouter from './api/controllers/service/router';
import careplanRouter from './api/controllers/careplan/router';
import careserviceRouter from './api/controllers/careservice/router';
import appointmentserviceRouter from './api/controllers/appointmentservice/router';
import careplandetailsRouter from './api/controllers/careplandetails/router';
import documentRouter from './api/controllers/document/router';
import carerdocumentRouter from './api/controllers/carerdocument/router';
import residentdocumentRouter from './api/controllers/residentdocument/router';
import profiledocumentRouter from './api/controllers/profiledocument/router';
import permissionsRouter from './api/controllers/permissions/router';
import profilepermissionRouter from './api/controllers/profilepermission/router';
import contacttypeRouter from './api/controllers/contacttype/router';
import contactRouter from './api/controllers/contact/router';
import jobtypeRouter from './api/controllers/jobtype/router';
export default function routes(app: Application): void {
  app.use('/v1/users', usersRouter);
  app.use('/v1/tenants/', tenantsRouter);
  app.use('/v1/auth/', authRouter);
  app.use('/v1/profiletype/', profiletypeRouter);
  app.use('/v1/addresstype/', addresstypeRouter);
  app.use('/v1/country/', countryRouter);
  app.use('/v1/profile/', profileRouter);
  app.use('/v1/nextofkin/', nextofkinRouter);
  app.use('/v1/address/', addressRouter);
  app.use('/v1/branch/', branchRouter);
  app.use('/v1/residentbranch/', residentbranchRouter);
  app.use('/v1/additionalnotes/', additionalnotesRouter);
  app.use('/v1/generalinfo/', generalinfoRouter);
  app.use('/v1/accommodationdetails/', accommodationdetailsRouter);
  app.use('/v1/carerskill/', carerskillRouter);
  app.use('/v1/carerspacialities/', carerspacialitiesRouter);
  app.use('/v1/role/', roleRouter);
  app.use('/v1/profilerole/', profileroleRouter);
  app.use('/v1/rating/', ratingRouter);
  app.use('/v1/availability/', availabilityRouter);
  app.use('/v1/employmentdetails/', employmentdetailsRouter);
  app.use('/v1/appointment/', appointmentRouter);
  app.use('/v1/appointedcarer/', appointedcarerRouter);
  app.use('/v1/plantypes/', plantypesRouter);
  app.use('/v1/service/', serviceRouter);
  app.use('/v1/careplan/', careplanRouter);
  app.use('/v1/careservice/', careserviceRouter);
  app.use('/v1/appointmentservice/', appointmentserviceRouter);
  app.use('/v1/careplandetails/', careplandetailsRouter);
  app.use('/v1/document/', documentRouter);
  app.use('/v1/carerdocument/', carerdocumentRouter);
  app.use('/v1/residentdocument/', residentdocumentRouter);
  app.use('/v1/profiledocument/', profiledocumentRouter);
  app.use('/v1/permissions/', permissionsRouter);
  app.use('/v1/profilepermission/', profilepermissionRouter);
  app.use('/v1/contacttype/', contacttypeRouter);
  app.use('/v1/contact/', contactRouter);
  app.use('/v1/job_type/', jobtypeRouter);
}
