swagger: "2.0"
info:
  version: 1.0.0
  title: carehome-core
  description: Carehome Microservices
basePath: /api/v1
tags:
  - name: Users
    description: Simple example endpoints
  - name: Tenants
    description: List of all Tenants
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  UserBody:
    type: object
    title: User
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /users:
    get:
      tags:
        - Users
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Users
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/UserBody"
      responses:
        200:
          description: Returns all examples
  
  /users/{id}:
    get:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /tenants/:
    get:
      tags:
        - Tenants
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification